### ISSUE TITLE
Building, cant load such file "textmate_grammar"

### ISSUE THREAD

**Issue by jeff-hykin** [jeff-hykin/experimental-cpp-syntax#2]
Courtesy of @MMesich-Nvidia 
![image](https://user-images.githubusercontent.com/17692058/107839840-10c65780-6d74-11eb-8b67-bf4e9a6582eb.png)

**Comment by jeff-hykin** [comment]
Thankfully this error isn't too bad to deal with. If exiting the project and re `nix-shell`-ing doesn't work try runing `bundle` and if it still doesn't work then I might try something more hacky.

The ruby bundler should be turning the `gem` folder in the repo into that textmate_grammar dependency (details in the Gemfile). So if it doesn't work, I'lll modify the code to require it directly.

**Comment by MMesich-Nvidia** [comment]
Hey Jeff, 

I have re `nix-shell`'d a number of times, but still encounter the build error mentioned above.  I have tried most of the other command available with no luck either.  Yet,  if I remove the cpp_cuda directory then I can build and run all the tests successfully.

I admit I am new to nix, ruby etc, but I cannot see how cpp_cuda is any different from cpp, and I am not completely sure how your build scripts are supposed to work.  So, it may be something simple and I just cannot see it!

If it were possible for you to get the project building with the cpp_cuda directory that would be really helpful.  I guess I could always start by collecting some examples, but I was hoping to augment the cpp_cuda scripts to get things working and then test it out on some examples.

Thanks,
Mark

**Comment by MMesich-Nvidia** [comment]
I also notice that if I update `source/languages/cpp/generate.rb` in any way, I get the same build error when I execute `npm run build`.  Is this the correct command?  Is there something else I should be doing instead?


Is there a step I am missing?

**Comment by jeff-hykin** [comment]
Sorry, the power/heat/internet outages have kept me decently busy.

The issue is still what is stated at the top, researching the ruby bundler and local/relaitve gems is probably the best way forward. Its probably going to take me more than 30 minutes to fix it, especially since I'm not sure whats causing your error. Its kind of like main.cpp with `include <stdlib.h>` and the `./stdlib.h` is two folders up. Its not complicated, and normally I'd just have to poke around on the machine to figure out what is going on as to why the build system isn't connecting things.

The cpp/c/objc difference is probably just placebo. The build command looks at what `generate.rb` files have been modified (according to git) and only builds things that have been modified since last build. So your build fails for everything

`ruby source/languages/cpp_cuda/generate.rb` is basically all the build is doing.

**Comment by MMesich-Nvidia** [comment]
Hey Jeff, 

I have done more digging today and thought I would share the current state. 

Both Elton and I are encountering the same issues over multiple machines and multiple environments.  I wont go into all the things I have tried, but I believe at the end of the day, we may simply be missing code in the private repository.

Today I noticed that it appeared that the **textmate_grammar** gem is not installed properly. For example, I can see it in the list from `gem list`, but if I enter `gem which textmate_grammar`, I get _"Error: Can't find Ruby library file or shared library textmate_grammar"_.  

Further inspection of the $GEM_HOME/gem/textmate_grammar-0.0.0 directory suggests that he code is indeed not there.  I only have a _LICENSE_ and _README.md_ file.  There is no _lib_ or _spec_ directory as expected.

Comparing the public repository (https://github.com/jeff-hykin/cpp-textmate-grammar), it looks like the _gem/lib_ directory did not make into the private repository I am working with.  I believe it may have been missed.  I will try to grab the files from there and try it with the private repository, but I would be grateful if you could confirm this approach.  Or, perhaps you can patch up the private repository to your liking.

In addition it would be nice to confirm the commands that are required to build the extension, and the order that they should be executed.  I have been trying to deduce them from the code, but confirmation on the workflow would be great.

Thanks again for your help and support,
Mark.

**Comment by MMesich-Nvidia** [comment]
Couple of new items:

Although the contents of _$GEM_HOME/gem/textmate_grammar-0.0.0_ directory seems incomplete at this time, I am not sure that it matters.

Copying over the lib directory from the public repository allowed me to get by my original error.  But then I ran into a similar error - **/home/mmesich/better-cpp-syntax/source/languages/cpp/generate.rb:15:in `require_relative': cannot load such file -- /home/mmesich/better-cpp-syntax/source/languages/cpp/lib/raw_strings.rb (LoadError)**.  It seems that the _lib_ directory is missing from _source/languages/cpp_ as well.

I then copied the lib directory from the public repository and things progressed.  I am still not sure things are working yet though. Here is why...

I updated one of the fileTypes in source/languages/cpp/generate.rb to be "cu".  But, when I run the extension and open a .cu file, there is no syntax highlighting.  Should this be sufficient to add support for .cu files?  I will continue to learn the code, but through this might be a good sanity test.

**Comment by jeff-hykin** [comment]
@MMesich-Nvidia  Thanks that additional info was helpful. I booted up a linux distro replicated the problem, made a lot of changes and it should be fixed now 👍 . The main issue was the newly merged in gitignore was causing the `lib/` folders not to sync, although there were a few other issues in grammar.rb that had only been fixed locally that were masked also because of the gitignore.

The `fileTypes` don't really affect anything in VS Code. Atom uses it and the testing framework uses it. To do what you wanted to, I went ahead and created a new  `cpp_cuda` language and added the language config under the /languages/cuda_cpp/language_config. The file you really want to edit will be `./package.json` (search for `cpp_cuda` there and you'll see the file extensions) and unlike the generate.rb section, adding extensions there will actually change things. The `./source/languages/cpp_cuda/package.json` is what is used when the extension is published, and it will be forcefully merged with the main `./package.json`. (This is part of the mess I've always wanted to clean up; multiple languages semi-automated in a single repo was a mistake, although thats how the code was when I inherited it)

#### Note
One of the other changes that was made is the startup command is now `./shell` instead of `nix-shell`. And now if you start the VS Code debugger, it'll build all the code before opening up a new window.

**Comment by MMesich-Nvidia** [comment]
Thanks Jeff!  This seems to be working as expected now.  Hopefully things will be a little more smooth sailing from here - but i know I will have more questions for you eventually!
